--- #YAML:1.0
name:               Device-VantagePro
version:            0.21
abstract:           Perl module to read and control a Davis Vantage Pro Weather Station
author:
    - root <root@localdomain>
license:            unknown
distribution_type:  module
configure_requires:
    ExtUtils::MakeMaker:  0
build_requires:
    ExtUtils::MakeMaker:  0
requires:  {}
no_index:
    directory:
        - t
        - inc
generated_by:       ExtUtils::MakeMaker version 6.56
meta-spec:
    url:      http://module-build.sourceforge.net/META-spec-v1.4.html
    version:  1.4
